Revert "tmp: for test"
This reverts commit b63ab3359d64a0b9324ca4bb08df2e5b33af9e64.

diff --git a/.github/workflows/perf-template.yml b/.github/workflows/perf-template.yml
--- a/.github/workflows/perf-template.yml
+++ b/.github/workflows/perf-template.yml
@@ -86,69 +86,69 @@ jobs:
         run: |
           python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --clean
 
-      # - name: Build EMU with DRAMsim3
-      #   run: |
-      #     if [ -e "$SPEC_DIR/emu" ]; then
-      #       mkdir -p $NOOP_HOME/build
-      #       cp $SPEC_DIR/emu $NOOP_HOME/build/emu
-      #     else
-      #       python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --build          \
-      #         --dramsim3 /nfs/home/share/ci-workloads/DRAMsim3              \
-      #         --with-dramsim3 --threads 16                                  \
-      #         --pgo $GITHUB_WORKSPACE/ready-to-run/coremark-2-iteration.bin \
-      #         --llvm-profdata llvm-profdata --trace-fst
-      #       mkdir -p $SPEC_DIR
-      #       cp $NOOP_HOME/build/emu $SPEC_DIR/emu
-      #     fi
+      - name: Build EMU with DRAMsim3
+        run: |
+          if [ -e "$SPEC_DIR/emu" ]; then
+            mkdir -p $NOOP_HOME/build
+            cp $SPEC_DIR/emu $NOOP_HOME/build/emu
+          else
+            python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --build          \
+              --dramsim3 /nfs/home/share/ci-workloads/DRAMsim3              \
+              --with-dramsim3 --threads 16                                  \
+              --pgo $GITHUB_WORKSPACE/ready-to-run/coremark-2-iteration.bin \
+              --llvm-profdata llvm-profdata --trace-fst
+            mkdir -p $SPEC_DIR
+            cp $NOOP_HOME/build/emu $SPEC_DIR/emu
+          fi
 
-      # - name: Run SPEC CPU2006 checkpoints
-      #   run: |
-      #     cd $PERF_HOME
-      #     python3 xs_autorun_multiServer.py $CKPT_HOME $CKPT_JSON_PATH \
-      #       --xs $NOOP_HOME --threads 16 --dir $SPEC_DIR --resume \
-      #       -L "$NODE_SERVER_LIST"
-      #     find $NOOP_HOME/build/ -maxdepth 1 -name "*.vcd" -exec mv {} $SPEC_DIR \;
-      #     find $NOOP_HOME/build/ -maxdepth 1 -name "*.fst" -exec mv {} $SPEC_DIR \;
+      - name: Run SPEC CPU2006 checkpoints
+        run: |
+          cd $PERF_HOME
+          python3 xs_autorun_multiServer.py $CKPT_HOME $CKPT_JSON_PATH \
+            --xs $NOOP_HOME --threads 16 --dir $SPEC_DIR --resume \
+            -L "$NODE_SERVER_LIST"
+          find $NOOP_HOME/build/ -maxdepth 1 -name "*.vcd" -exec mv {} $SPEC_DIR \;
+          find $NOOP_HOME/build/ -maxdepth 1 -name "*.fst" -exec mv {} $SPEC_DIR \;
 
-      # - name: Report SPEC CPU2006 score
-      #   if: always()
-      #   run: |
-      #     cd $PERF_HOME
-      #     python3 xs_autorun_multiServer.py $CKPT_HOME $CKPT_JSON_PATH \
-      #       --xs $NOOP_HOME --threads 16 --dir $SPEC_DIR \
-      #       --check --dump-json-path $SPEC_DIR/err_ckps.json
-      #     python3 xs_autorun_multiServer.py $CKPT_HOME $CKPT_JSON_PATH \
-      #       --xs $NOOP_HOME --threads 16 --dir $SPEC_DIR --report \
-      #       > $SPEC_DIR/score.txt
-      #     # mkdir $GITHUB_WORKSPACE/result
-      #     # cp $SPEC_DIR/err_ckps.json $GITHUB_WORKSPACE/result/err_ckps.json
-      #     # cp $SPEC_DIR/score.txt $GITHUB_WORKSPACE/result/score.txt
+      - name: Report SPEC CPU2006 score
+        if: always()
+        run: |
+          cd $PERF_HOME
+          python3 xs_autorun_multiServer.py $CKPT_HOME $CKPT_JSON_PATH \
+            --xs $NOOP_HOME --threads 16 --dir $SPEC_DIR \
+            --check --dump-json-path $SPEC_DIR/err_ckps.json
+          python3 xs_autorun_multiServer.py $CKPT_HOME $CKPT_JSON_PATH \
+            --xs $NOOP_HOME --threads 16 --dir $SPEC_DIR --report \
+            > $SPEC_DIR/score.txt
+          # mkdir $GITHUB_WORKSPACE/result
+          # cp $SPEC_DIR/err_ckps.json $GITHUB_WORKSPACE/result/err_ckps.json
+          # cp $SPEC_DIR/score.txt $GITHUB_WORKSPACE/result/score.txt
 
-      # - name: Summary result
-      #   if: always()
-      #   run: |
-      #     echo "### :rocket: Performance Test Result" >> $GITHUB_STEP_SUMMARY
-      #     echo '```' >> $GITHUB_STEP_SUMMARY
-      #     echo "$SPEC_DIR/score.txt" >> $GITHUB_STEP_SUMMARY
-      #     tail -n 39 $SPEC_DIR/score.txt >> $GITHUB_STEP_SUMMARY
-      #     echo '```' >> $GITHUB_STEP_SUMMARY
+      - name: Summary result
+        if: always()
+        run: |
+          echo "### :rocket: Performance Test Result" >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          echo "$SPEC_DIR/score.txt" >> $GITHUB_STEP_SUMMARY
+          tail -n 39 $SPEC_DIR/score.txt >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
           
-      #     echo "### :rainbow: Key Indicators" >> $GITHUB_STEP_SUMMARY
-      #     echo "Estimated SPEC CPU2006 Score per GHz: " >> $GITHUB_STEP_SUMMARY
-      #     TOTAL_SCORE=$(grep "SPEC2006/GHz:" $SPEC_DIR/score.txt | awk '{print $NF}')
-      #     INT_SCORE=$(grep "SPECint2006/GHz:" $SPEC_DIR/score.txt | awk '{print $NF}')
-      #     FP_SCORE=$(grep "SPECfp2006/GHz:" $SPEC_DIR/score.txt | awk '{print $NF}')
-      #     echo "- int: **${INT_SCORE}**" >> $GITHUB_STEP_SUMMARY
-      #     echo "- fp: **${FP_SCORE}**" >> $GITHUB_STEP_SUMMARY
-      #     echo "- total: **${TOTAL_SCORE}**" >> $GITHUB_STEP_SUMMARY
+          echo "### :rainbow: Key Indicators" >> $GITHUB_STEP_SUMMARY
+          echo "Estimated SPEC CPU2006 Score per GHz: " >> $GITHUB_STEP_SUMMARY
+          TOTAL_SCORE=$(grep "SPEC2006/GHz:" $SPEC_DIR/score.txt | awk '{print $NF}')
+          INT_SCORE=$(grep "SPECint2006/GHz:" $SPEC_DIR/score.txt | awk '{print $NF}')
+          FP_SCORE=$(grep "SPECfp2006/GHz:" $SPEC_DIR/score.txt | awk '{print $NF}')
+          echo "- int: **${INT_SCORE}**" >> $GITHUB_STEP_SUMMARY
+          echo "- fp: **${FP_SCORE}**" >> $GITHUB_STEP_SUMMARY
+          echo "- total: **${TOTAL_SCORE}**" >> $GITHUB_STEP_SUMMARY
 
-      #     if ! grep -q '^{\s*}$' $SPEC_DIR/err_ckps.json; then
-      #       echo "### :sos: Failed Tests" >> $GITHUB_STEP_SUMMARY  
-      #       echo '```' >> $GITHUB_STEP_SUMMARY
-      #       cat $SPEC_DIR/err_ckps.json >> $GITHUB_STEP_SUMMARY
-      #       echo "" >> $GITHUB_STEP_SUMMARY
-      #       echo '```' >> $GITHUB_STEP_SUMMARY
-      #     fi
+          if ! grep -q '^{\s*}$' $SPEC_DIR/err_ckps.json; then
+            echo "### :sos: Failed Tests" >> $GITHUB_STEP_SUMMARY  
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            cat $SPEC_DIR/err_ckps.json >> $GITHUB_STEP_SUMMARY
+            echo "" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+          fi
 
       # - name: Upload result
       #   uses: actions/upload-artifact@v4
