ci(perf): upgrade to using GITHUB_OUTPUT

diff --git a/.github/workflows/perf.yml b/.github/workflows/perf.yml
--- a/.github/workflows/perf.yml
+++ b/.github/workflows/perf.yml
@@ -28,7 +28,7 @@ jobs:
       - name: Determine if this is the biweekly run
         id: determine_run
         run: |
-          [ $(( $(date +'%V') % 2 )) -eq 0 ] && echo "::set-output name=run_biweekly::true" || echo "::set-output name=run_biweekly::false"
+          [ $(( $(date +'%V') % 2 )) -eq 0 ] && echo "run_biweekly::true" >> $GITHUB_OUTPUT || echo "run_biweekly::false" >> $GITHUB_OUTPUT
 
       - name: Set test commit
         id: set_test_commit
@@ -36,10 +36,10 @@ jobs:
         run: |
           if [ "${{ github.event.inputs.test_commit }}" = "" ]; then
             echo "Using latest commit."
-            echo "::set-output name=commit_sha::${{ github.sha }}"
+            echo "commit_sha::${{ github.sha }}" >> $GITHUB_OUTPUT
           else
             echo "Using specified commit: ${{ github.event.inputs.test_commit }}"
-            echo "::set-output name=commit_sha::${{ github.event.inputs.test_commit }}"
+            echo "commit_sha::${{ github.event.inputs.test_commit }}" >> $GITHUB_OUTPUT
           fi
 
       - name: Checkout code at specific commit
@@ -69,6 +69,10 @@ jobs:
           mkdir -p $NOOP_HOME/build
           echo "hello world" > $NOOP_HOME/build/test.log
 
+      # - name: Clean Up
+      #   if: steps.determine_run.outputs.run_biweekly == 'true'
+      #   run: |
+      #     python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --clean
       # - name: Build EMU with DRAMsim3
       #   if: steps.determine_run.outputs.run_biweekly == 'true'
       #   run: |
@@ -76,7 +80,6 @@ jobs:
       #       mkdir -p $NOOP_HOME/build
       #       cp $SPEC_DIR/emu $NOOP_HOME/build/emu
       #     else
-      #       python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --clean
       #       python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --build          \
       #         --dramsim3 /nfs/home/share/ci-workloads/DRAMsim3              \
       #         --with-dramsim3 --threads 16                                  \
