feat(perf_trigger): add --dry-run function and spectag for constantin

diff --git a/.github/workflows/perf-template.yml b/.github/workflows/perf-template.yml
--- a/.github/workflows/perf-template.yml
+++ b/.github/workflows/perf-template.yml
@@ -102,7 +102,6 @@ jobs:
           SHORT_SHA=$(git rev-parse --short HEAD)
           DATE=$(git show -s --format=%cd --date=format:%y%m%d HEAD)
           echo "SCRIPTS_HOME=/nfs/home/share/ci-workloads/env-scripts" >> $GITHUB_ENV
-          SPEC_DIR="${{ inputs.perf_report_dir }}/cr${DATE}-${SHORT_SHA}-${{ inputs.xs_config }}"
           echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_OUTPUT
           echo "DATE=${DATE}" >> $GITHUB_OUTPUT
           
@@ -116,23 +115,26 @@ jobs:
             echo "SERVER_LIST=${{ inputs.servers }}" >> $GITHUB_ENV
           fi
 
-          # Set CST_COMPILE_FLAGS and CST_RUN_FLAGS based on cst_file
+          SPEC_TAG="-${{ inputs.xs_config }}"
+          # Set CST_COMPILE_OPT and CST_RUN_OPT based on cst_file
           if [[ -n "${{ inputs.cst_file }}" ]]; then
             if [[ ! -f "${{ inputs.cst_file }}" ]]; then
               echo "Error: cst_file does not exist: ${{ inputs.cst_file }}"
               exit 1
             fi
-            echo "CST_COMPILE_FLAGS=--with-constantin" >> $GITHUB_ENV
-            echo "CST_RUN_FLAGS=--cst-file ${{ inputs.cst_file }}" >> $GITHUB_ENV
-            SPEC_DIR=${SPEC_DIR}-cst
+            CONST_BASENAME=$(basename "${{ inputs.cst_file }}")
+            CONST_TAG=${CONST_BASENAME%.*}
+            SPEC_TAG="${SPEC_TAG}-${CONST_TAG}"
+
+            echo "CST_COMPILE_OPT=--with-constantin" >> $GITHUB_ENV
+            echo "CST_RUN_OPT=--cst-file ${{ inputs.cst_file }}" >> $GITHUB_ENV
           else
-            echo "CST_COMPILE_FLAGS=" >> $GITHUB_ENV
-            echo "CST_RUN_FLAGS=" >> $GITHUB_ENV
+            echo "CST_COMPILE_OPT=" >> $GITHUB_ENV
+            echo "CST_RUN_OPT=" >> $GITHUB_ENV
           fi
+          SPEC_DIR="${{ inputs.perf_report_dir }}/cr${DATE}-${SHORT_SHA}${SPEC_TAG}"
 
-          echo "SPEC_DIR=${SPEC_DIR}" >> $GITHUB_ENV
-          echo "SPEC_DIR=${SPEC_DIR}" >> $GITHUB_OUTPUT
-
+          DRY_RUN_OPT=""
           case "${{ inputs.benchmark_type }}" in
             "gcc15-spec06-0.3c")
               echo "CKPT_JSON_PATH=/nfs/home/share/ci-workloads/json/gcc15-spec06-0.3.json" >> $GITHUB_ENV
@@ -174,7 +176,25 @@ jobs:
               echo "CKPT_JSON_PATH=${{ inputs.json_path }}" >> $GITHUB_ENV
               echo "CKPT_HOME=${{ inputs.checkpoint_path }}" >> $GITHUB_ENV
               ;;
+            "dryrun")
+              echo "CKPT_JSON_PATH=/nfs/home/share/ci-workloads/json/dryrun.json" >> $GITHUB_ENV
+              echo "CKPT_HOME=/nfs/home/share/checkpoints_profiles/spec06_rv64gcb_O3_20m_gcc12.2.0-intFpcOff-jeMalloc/checkpoint-0-0-0" >> $GITHUB_ENV
+
+              echo "dryrun testing:"
+              echo "    default SPEC_DIR: ${SPEC_DIR}"
+              SPEC_DIR="${{ inputs.perf_report_dir }}/dryrun${SPEC_TAG}"
+              echo "    dryrun SPEC_DIR: ${SPEC_DIR}"
+              DRY_RUN_OPT="--dry-run"
+              ;;
+            *)
+              echo "Error: Invalid benchmark_type: ${{ inputs.benchmark_type }}"
+              exit 1
+              ;;
           esac
+
+          echo "SPEC_DIR=${SPEC_DIR}" >> $GITHUB_ENV
+          echo "SPEC_DIR=${SPEC_DIR}" >> $GITHUB_OUTPUT
+          echo "DRY_RUN_OPT=${DRY_RUN_OPT}" >> $GITHUB_ENV
 
       - name: Initialize submodules
         run: make init-force
@@ -192,7 +212,8 @@ jobs:
               --threads $([ "${{ inputs.emulator }}" = "gsim" ] && echo 1 || echo 8) \
               --pgo $GITHUB_WORKSPACE/ready-to-run/coremark-2-iteration.bin \
               --llvm-profdata llvm-profdata --trace-fst \
-              --emulator ${{ inputs.emulator }} $CST_COMPILE_FLAGS
+              --emulator ${{ inputs.emulator }} \
+              $CST_COMPILE_OPT
             mkdir -p $SPEC_DIR
             cp $GITHUB_WORKSPACE/build/emu $SPEC_DIR/emu
           fi
@@ -210,7 +231,8 @@ jobs:
             --server-list "$SERVER_LIST" \
             --nemu-so-path $SPEC_DIR/riscv64-nemu-interpreter-so \
             --log-level ${{ runner.debug && 'DEBUG' || 'INFO' }} \
-            --run $CST_RUN_FLAGS
+            --run \
+            $CST_RUN_OPT $DRY_RUN_OPT
 
       - name: Report SPEC CPU2006 score
         if: always()
